[tox]
minversion = 3.0
envlist = py39-ansible215
skipsdist = true

[testenv]
passenv = *
deps =
    -r tox-requirements.txt
    ansible-core>=2.15,<2.16
commands =
    {posargs:molecule test -s podman --destroy always}