#SPDX-License-Identifier: MIT-0
---
- name: "Add Vector repository via DEB822"
  ansible.builtin.deb822_repository:
    name: "vector"
    types: ["deb"]
    uris: ["{{ apt_vector_repository_url }}"]
    suites: ["{{ vector_dist_channel }}"]
    components: ["vector-{{ vector_major_version }}"]
    signed_by: "{{ apt_vector_gpg_key_url }}"

